# Generated by Django 4.2.24 on 2025-09-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='ShopProduct',
        ),
    ]
