# Generated by Django 4.2.24 on 2025-09-13 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_news_shopproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('aksesoris', 'Aksesoris'), ('topi', 'Topi'), ('ball', 'Bola Tendang'), ('kaos kaki', 'Kaos Kaki')], default='update', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('rating_product', models.IntegerField()),
                ('size_product', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ShopProduct',
        ),
    ]
