# Generated by Django 4.2.24 on 2025-09-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_product_delete_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('update', 'Update'), ('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('aksesoris', 'Aksesoris'), ('topi', 'Topi'), ('ball', 'Bola Tendang'), ('kaos_kaki', 'Kaos Kaki')], default='update', max_length=20),
        ),
    ]
