# Generated by Django 4.2.24 on 2025-09-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_user_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('update', 'Update'), ('jersey', 'Jersey'), ('sepatu', 'Shoes'), ('aksesoris', 'Accessories'), ('topi', 'Hat'), ('ball', 'Football'), ('kaos_kaki', 'Socks')], default='update', max_length=20),
        ),
    ]
